version: '3.5'

services:
  postgres:
    container_name: my_flowchart_pgsql
    image: postgres
    environment:
      POSTGRES_USER: ${PG_USER}
      POSTGRES_PASSWORD: ${PG_PASSWORD}
      POSTGRES_DB: ${PG_DB_NAME}
      PGDATA: /data/postgres
    volumes:
       - postgres:/data/postgres
    ports:
       - 5435:5432
    expose:
       - 5435
    networks:
      - postgres
    restart: unless-stopped

networks:
  postgres:
    driver: bridge

volumes:
    postgres: